DROP TABLE IF EXISTS ACCOUNT;
CREATE TABLE ACCOUNT
(
	ACCOUNT_ID            VARCHAR(10) NOT NULL,
	ACCOUNT_TYPE          VARCHAR(45),
	ACCOUNT_OPEN_DATE     VARCHAR(45),
	ACCOUNT_CLOSE_DATE    VARCHAR(45)
);